# syntax=docker/dockerfile:1

## Build

FROM golang:1.18 AS build

WORKDIR /api

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY *.go ./

RUN go build -o ./bin/main

## Deploy

FROM gcr.io/distroless/base-debian11

WORKDIR /

COPY --from=build /api/bin/ ./

EXPOSE 8080

CMD [ "./main" ]