
services:
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.multi
    container_name: apidb
    ports:
      - 8080:8080
    env_file: .env
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - roach:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-qwerty}

volumes:
  roach:

networks:
  mynet:
    driver: bridge